server:
  port: 8081
logging:
  level:
    cn.light.web: debug

light:
  title: lightTitle
  content: lightContent


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: shiro
    username: shiro
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true