server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: shiro
    username: shiro
    driver-class-name: com.mysql.jdbc.Driver

#当mybatis的xml文件和mapper接口不在相同包下时，需要用mapperLocations属性指定xml文件的路径。
#*是个通配符，代表所有的文件，**代表所有目录下
mybatis:
  mapper-locations: classpath:mappers/*.xml

